name: icevision
channels:
  - pytorch
  - fastai
  - defaults
dependencies:
  - pillow >8.0.0,<9
  - python>3.6,<4
  - pytorch==1.10.0
  - torchvision==0.11.1
  - cudatoolkit=10.2
  - fastcore >=1.3.0,<1.4
  - fastai >=2.5.2,<2.6
  - pip
  - pip:
      - icevision[all]==0.12.0
      - --find-links https://download.openmmlab.com/mmcv/dist/cu102/torch1.10.0/index.html
      - mmcv-full==1.3.17
      - mmdet==2.17.0
      - rasterio>=1.3.0, <2
