site_name: Mantisshrimp
theme:
  name: 'material'
  palette:
    scheme: default # default slate
    primary: 'blue'
    accent: 'blue'

docs_dir: sources
repo_url: https://github.com/lgvaz/Mantisshrimp
site_url: https://lgvaz.github.io/mantisshrimp/
edit_uri: ""
site_description: 'Documentation for Mantisshrimp.'
# google_analytics: ['UA-44322747-3', 'https://lgvaz.github.io/mantisshrimp/']
markdown_extensions:
  - codehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition

extra_javascript:
  - https://unpkg.com/mermaid@8.4.4/dist/mermaid.min.js

nav:
  - Home: index.md
  - Installation: install.md
  - Docker: docker.md
  - Tutorials:
    - Getting Started: getting_started.md
    - Custom Parser: custom_parser.md
    - Advanced Guide: advanced_guide.md
  - Examples:
    - Training: examples/training.md
    - Inference: examples/inference.md
  - Deployment: deployment.md
  - Contributing Guide: contributing.md
  - Generating Docs: readme_mkdocs.md
  - Preferences:
    - Changing the colors: changing-the-colors.md    
  - About: about.md
