site_name: IceVision
site_author: Lucas Goulart Vazquez, Farid Hassainia, and Contributors
copyright: airctic.com
theme:
  name: 'material'
  palette:
    scheme: default # default slate
    primary: 'blue'
    accent: 'blue'

docs_dir: sources
repo_url: https://github.com/airctic/IceVision
site_url: https://airctic.com/
edit_uri: ""
site_description: 'Documentation for IceVision.'
# google_analytics: ['UA-44322747-3', 'https://airctic.github.io/icevision/']
markdown_extensions:
  - codehilite
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.tabbed
  - attr_list
extra:
  manifest: manifest.webmanifest
extra_css:
- css/termynal.css
- css/custom.css
extra_javascript:
- https://unpkg.com/mermaid@8.4.6/dist/mermaid.min.js
- js/termynal.js
- js/custom.js
- https://cdn.jsdelivr.net/npm/@widgetbot/crate@3
- js/crate.js

nav:
  - Home: index.md
  - Installation: install.md
  - Tutorials:
    - Getting Started: getting_started.md
    - Getting Started with MMDetection: getting_started_mmdetection.md
    - Quickstart using EfficientDet: quickstart.md
    - Quickstart using RetinaNet: retinanet.md
    - Custom Parser: custom_parser.md
    - Inference: inference.md
    - Mask RCNN: mask_rcnn_pennfudan.md
    - Keypoints RCNN: ochuman_keypoint_detection.md
    - EffecientDet: efficientdet_pets.md
    - Training a VOC dataset: dataset_voc_nb.md
    - Model Tracking Using Wandb: wandb_efficientdet.md
    - How to use negative samples: negative_samples.md
    - Fixed Splitter: voc_predefined_splits.md
  - Examples:
    - Getting Started: examples/getting_started_exp.md
    - Quickstart: examples/quickstart_exp.md
    - Inference: examples/inference_exp.md
    - EffecientDet: examples/efficientdet_pets_exp.md
    - Mask RCNN: examples/mask_rcnn_pennfudan_exp.md
    - Training a VOC dataset: examples/dataset_voc_exp.md
    - Backbones - Faster RCNN: examples/backbones_faster_rcnn.md
  - Transforms:
    - Albumentations: albumentations.md 
  - Models:
    - EffecientDet: model_efficientdet.md
    - Faster RCNN: model_faster_rcnn.md
    - Models Comparison: model_comparison.md
  - Backbones:
    - EffecientDet: backbones_effecientdet.md
    - Faster/Mask RCNN: backbones_faster_mask_rcnn.md
  - Deployment: 
    - Overview: deployment.md
    - Gradio:
      - COCO: IceApp_coco.md
      - PETS: IceApp_pets.md
      - Masks: IceApp_masks.md
  - API Documentation:
    - Parser: parser.md
    - Dataset: dataset.md
    - Transforms:
      - Albumentations: albumentations_tfms.md
    - Models:
      - Faster RCNN:
        - common: faster_rcnn.md
        - fastai: faster_rcnn_fastai.md
        - lightning: faster_rcnn_lightning.md
      - Mask RCNN:
        - common: mask_rcnn.md
        - fastai: mask_rcnn_fastai.md
        - lightning: mask_rcnn_lightning.md
      - EfficientDet:
        - common: efficientdet.md
        - fastai: efficientdet_fastai.md
        - lightning: efficientdet_lightning.md
      # - Metrics:
      #   - COCOMetric: coco_metric.md
    - Data Splitters: data_splits.md
  - How-To: how-to.md
  - Contributing Guide: contributing.md
  - Generating Docs: readme_mkdocs.md
  - Preferences:
    - Changing the colors: changing_the_colors.md    
  - Code of Conduct: code_of_conduct.md
  - About: about.md
