site_name: Mantisshrimp
theme:
  name: 'material'
  palette:
    scheme: default # default slate
    primary: 'blue'
    accent: 'blue'

docs_dir: sources
repo_url: https://github.com/airctic/Mantisshrimp
site_url: https://airctic.github.io/mantisshrimp/
edit_uri: ""
site_description: 'Documentation for Mantisshrimp.'
# google_analytics: ['UA-44322747-3', 'https://airctic.github.io/mantisshrimp/']
markdown_extensions:
  - codehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition

extra_javascript:
  - https://unpkg.com/mermaid@8.4.4/dist/mermaid.min.js

nav:
  - Home: index.md
  - Installation: install.md
  - Docker: docker.md
  - Tutorials:
    - Getting Started: getting_started.md
    - Custom Parser: custom_parser.md
    - EffecientDet: efficientdet_pets.md
    - Training a dataset: how_train_dataset.md
  - Models:
    - Faster RCNN: model_faster_rcnn.md
  - Examples:
    - Training: examples/training.md
    - Inference: examples/inference.md
    - EffecientDet: examples/effecientdet_pets_exp.md
    - Training a dataset: examples/how_train_dataset_exp.md
  - Deployment: deployment.md
  - API Documentation:
    - Parser: parser.md
    - Dataset: dataset.md
    - Transforms:
      - Albumentations: albumentations_tfms.md
    - Models:
      - Faster RCNN:
        - common: faster_rcnn.md
        - fastai: faster_rcnn_fastai.md
        - lightning: faster_rcnn_lightning.md
      - Mask RCNN:
        - common: mask_rcnn.md
        - fastai: mask_rcnn_fastai.md
        - lightning: mask_rcnn_lightning.md
      - EfficientDet:
        - common: efficientdet.md
        - fastai: efficientdet_fastai.md
        - lightning: efficientdet_lightning.md
      # - Metrics:
      #   - COCOMetric: coco_metric.md
      - Data Splitters: data_splits.md
  - Contributing Guide: contributing.md
  - Generating Docs: readme_mkdocs.md
  - Preferences:
    - Changing the colors: changing-the-colors.md    
  - About: about.md
